### PR TITLE
Adding Pixel 3 XL

### PR DESCRIPTION
**Pull request by azmartone**
Using Display Metrics App

2960x1440 pixels
5.3 x 2.6 inches

xdpi 558.490566
ydpi 553.8461538

### CODE REVIEW

**Comment by azmartone** [comment]
fixes #42

**Comment by azmartone** [comment]
Hey @cvan @thoragio , when you're free, want to review this PR?

**Comment by jsantell** [comment]
Looks good to me! Could you rebase, or not include the minified json?

**Comment by azmartone** [comment]
Rebased and omitted dpdb.json

**Comment by jsantell** [comment]
@azmartone thank you!

**Pull request merged**
